---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-api
  namespace: prod-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: atlas
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
      - name: prod-api
        image: amb0u/atlas-api:168
        ports:
        - containerPort: 8080
        env:
        - name: API_HOST
          valueFrom:
            secretKeyRef:
              key: API_HOST
              name: api-credentials
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: DB_PWD
              name: api-credentials
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              key: DB_URL
              name: api-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: api-credentials
        - name: FASTSPRING_PWD
          valueFrom:
            secretKeyRef:
              key: FASTSPRING_PWD
              name: api-credentials
        - name: FASTSPRING_USER
          valueFrom:
            secretKeyRef:
              key: FASTSPRING_USER
              name: api-credentials
        - name: FRONT_URL
          valueFrom:
            secretKeyRef:
              key: FRONT_URL
              name: api-credentials
        - name: GCP_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: GCP_BUCKET_NAME
              name: api-credentials
        - name: GCP_JSON
          valueFrom:
            secretKeyRef:
              key: GCP_JSON
              name: api-credentials
        - name: GCP_PROJECT_ID
          valueFrom:
            secretKeyRef:
              key: GCP_PROJECT_ID
              name: api-credentials
        - name: MAIL_RECIPIENTS
          valueFrom:
            secretKeyRef:
              key: MAIL_RECIPIENTS
              name: api-credentials
        - name: SMTP_PWD
          valueFrom:
            secretKeyRef:
              key: SMTP_PWD
              name: api-credentials
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              key: SMTP_USER
              name: api-credentials
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              key: SPRING_PROFILES_ACTIVE
              name: api-credentials
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET_KEY
              name: api-credentials      
        resources:
          #limits:
            #cpu: "4"
            #memory: "8Gi"
          requests:
            cpu: "2"
            memory: "3Gi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: v1
kind: Service
metadata:
  name:  prod-api
  namespace: prod-api
spec:
  selector:
    app: atlas
  type:  ClusterIP
  ports:
  - name:  http
    port:  8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-api
  namespace: prod-api
spec:
  rules:
  - host: "api.atlascmms.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-api
            port:
              number: 8080
