---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web
  namespace: prod-web
spec:
  replicas: 0
  selector:
    matchLabels:
      app: prod-web
  template:
    metadata:
      labels:
        app: prod-web
    spec:
      containers:
      - name: prod-web
        image: amb0u/react-app:155
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            secretKeyRef:
              key: REACT_APP_API_URL
              name: web-credentials
        - name: REACT_APP_GOOGLE_KEY
          valueFrom:
            secretKeyRef:
              key: REACT_APP_GOOGLE_KEY
              name: web-credentials
        - name: REACT_APP_GOOGLE_TRACKING_ID
          valueFrom:
            secretKeyRef:
              key: REACT_APP_GOOGLE_TRACKING_ID
              name: web-credentials
        - name: REACT_APP_JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: REACT_APP_JWT_SECRET_KEY
              name: web-credentials
        resources:
          limits:
            cpu: "3" #2
            memory: "7Gi" #4
          requests:
            cpu: "3" #3
            memory: "7Gi" #4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---
apiVersion: v1
kind: Service
metadata:
  name:  prod-web
  namespace: prod-web
spec:
  selector:
    app: prod-web
  type:  ClusterIP
  ports:
  - name:  http
    port:  3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-web
  namespace: prod-web
spec:
  rules:
  - host: "dev.atlascmms.com"
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-web
            port:
              number: 3000
  - host: "www.atlascmms.com"
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-web
            port:
              number: 3000
